"""
Models for Phase 6-L legal analysis, audit trail, and 6-F6 extraction audit.
"""
from sqlalchemy import Column, String, DateTime, func, JSON, ForeignKey, Boolean, Integer, Float
from sqlalchemy.dialects.postgresql import UUID
from app.db.base import Base
import uuid


class LegalAnalysis(Base):
    """Stores contract risk reports generated by POST /legal/contracts/{id}/risk-report."""
    __tablename__ = "legal_analyses"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    workspace_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    document_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    contract_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    user_id = Column(UUID(as_uuid=True), nullable=True, index=True)

    overall_risk_score = Column(Integer, nullable=True)
    overall_risk_level = Column(String, nullable=True)
    summary = Column(String, nullable=True)
    clause_risks = Column(JSON, default=list)
    missing_clauses = Column(JSON, default=list)
    consistency_warnings = Column(JSON, default=list)
    escalation_required = Column(Boolean, default=False)
    escalation_reason = Column(String, nullable=True)

    # Task 6-L6 — audit metadata
    model_version = Column(String, nullable=True)
    analysis_version = Column(String, default="v1.0")
    ip_address = Column(String, nullable=True)
    request_timestamp = Column(DateTime(timezone=True), nullable=True)
    response_duration_ms = Column(Integer, nullable=True)
    clause_count = Column(Integer, nullable=True)
    missing_clause_count = Column(Integer, nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now())


class LegalAuditLog(Base):
    """
    Immutable audit log — INSERT ONLY.
    No UPDATE or DELETE operations are permitted on this table.
    """
    __tablename__ = "legal_audit_log"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    user_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    document_id = Column(UUID(as_uuid=True), nullable=True)
    analysis_id = Column(UUID(as_uuid=True), nullable=True)
    # "analysis_created" | "report_exported" | "session_shared" | "escalation_triggered"
    event_type = Column(String, nullable=False)
    event_detail = Column(JSON, default=dict)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)


class ExtractionAudit(Base):
    """
    Task 6-F6: Character-level traceability for financial extractions.
    Each row links one extracted financial line item back to the exact source text.
    """
    __tablename__ = "extraction_audit"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, index=True)
    document_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    session_id = Column(UUID(as_uuid=True), nullable=True)
    line_item = Column(String, nullable=False)
    extracted_value = Column(Float, nullable=True)
    raw_text_span = Column(String, nullable=True)
    page_number = Column(Integer, nullable=True)
    table_row = Column(String, nullable=True)
    table_column = Column(String, nullable=True)
    confidence = Column(Float, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
