import io
import json
import logging
from datetime import datetime
from typing import Literal

logger = logging.getLogger(__name__)

_AUDIT_DISCLAIMER = (
    "This report was generated with AI assistance. "
    "All answers are grounded in the cited documents. "
    "Trust scores indicate retrieval confidence, not legal or professional certainty. "
    "All critical decisions must be independently verified by a qualified professional."
)


def _parse_message(content: str) -> dict:
    """Extract answer, evidence, trust, warnings from stored assistant message JSON."""
    try:
        parsed = json.loads(content)
        return {
            "answer": parsed.get("answer", content),
            "evidence": parsed.get("evidence", []),
            "confidence_score": parsed.get("confidence_score", 0.0),
            "trust": parsed.get("trust", None),
        }
    except Exception:
        return {"answer": content, "evidence": [], "confidence_score": 0.0, "trust": None}


def _trust_level(trust: dict | None, confidence: float) -> str:
    if trust and trust.get("level"):
        return trust["level"]
    if confidence >= 0.85:
        return "HIGH"
    if confidence >= 0.55:
        return "MEDIUM"
    return "LOW"


def _trust_score(trust: dict | None, confidence: float) -> int:
    if trust and trust.get("final_score") is not None:
        return int(trust["final_score"])
    return int(confidence * 100)


def generate_session_audit_report(
    session,
    user: dict,
    fmt: Literal["pdf", "docx"] = "pdf",
) -> io.BytesIO:
    """
    Build a structured audit trail report for the given session.
    Returns a BytesIO stream of the rendered file.

    Args:
        session: ChatSession ORM object with .messages, .title, .workspace_type, .created_at loaded.
        user: dict with "id", "email", and optionally "display_name" or "name".
        fmt: "pdf" or "docx".
    """
    if fmt == "pdf":
        return _build_pdf(session, user)
    return _build_docx(session, user)


# ── PDF ───────────────────────────────────────────────────────────────────────

def _build_pdf(session, user: dict) -> io.BytesIO:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    user_name = user.get("display_name") or user.get("name") or user.get("email", "Unknown")
    user_id_tail = str(user.get("id", ""))[-8:]
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # ── Collect document filenames from evidence ──────────────────────────────
    doc_filenames: list[str] = []
    msg_pairs: list[tuple[str, str, dict]] = []  # (query, timestamp, parsed_assistant)

    messages = list(session.messages)
    i = 0
    while i < len(messages):
        msg = messages[i]
        if msg.role == "user":
            query_text = msg.content
            ts = msg.created_at.strftime("%Y-%m-%d %H:%M") if msg.created_at else "—"
            ai_data: dict = {}
            if i + 1 < len(messages) and messages[i + 1].role == "assistant":
                ai_data = _parse_message(messages[i + 1].content)
                for ev in ai_data.get("evidence", []):
                    fn = ev.get("filename", "")
                    if fn and fn not in doc_filenames:
                        doc_filenames.append(fn)
                i += 1
            msg_pairs.append((query_text, ts, ai_data))
        i += 1

    # ── COVER PAGE ────────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 14, "AI-Assisted Document Analysis Report", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 7, "Generated by DocuMindAI", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(8)

    meta = [
        ("Session", session.title[:80]),
        ("Date", generated_at),
        ("Workspace", session.workspace_type.capitalize()),
        ("Documents analyzed", ", ".join(doc_filenames) if doc_filenames else "—"),
        ("User", f"{user_name} (ID: ...{user_id_tail})"),
    ]
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    for label, value in meta:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(50, 7, f"{label}:", new_x="RIGHT", new_y="TOP")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 7, value or "—")

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(100, 60, 0)
    pdf.multi_cell(0, 5, f"DISCLAIMER: {_AUDIT_DISCLAIMER}")
    pdf.set_text_color(0, 0, 0)

    # ── QUERY PAGES ──────────────────────────────────────────────────────────
    stats = {"total": 0, "high": 0, "medium": 0, "low": 0, "contradictions": 0}

    for n, (query_text, ts, ai_data) in enumerate(msg_pairs, 1):
        pdf.add_page()
        stats["total"] += 1

        level = _trust_level(ai_data.get("trust"), ai_data.get("confidence_score", 0.0))
        score = _trust_score(ai_data.get("trust"), ai_data.get("confidence_score", 0.0))
        stats[level.lower()] = stats.get(level.lower(), 0) + 1

        contradictions = (ai_data.get("trust") or {}).get("contradictions", [])
        stats["contradictions"] += len(contradictions)

        # Section divider
        pdf.set_draw_color(180, 180, 180)
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 8, f"Query #{n} — {ts}", new_x="LMARGIN", new_y="NEXT", border="B")
        pdf.ln(3)
        pdf.set_text_color(0, 0, 0)

        # Question
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Question:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_fill_color(245, 245, 245)
        pdf.multi_cell(0, 6, query_text, fill=True)
        pdf.ln(3)

        # Answer
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Answer:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        answer_clean = (
            (ai_data.get("answer") or "—")
            .replace("**", "").replace("*", "").replace("###", "")
            .replace("##", "").replace("#", "").replace("`", "")
        )
        pdf.multi_cell(0, 6, answer_clean)
        pdf.ln(2)

        # Trust Score
        level_colors = {"HIGH": (22, 163, 74), "MEDIUM": (180, 83, 9), "LOW": (220, 38, 38)}
        r, g, b = level_colors.get(level, (80, 80, 80))
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(r, g, b)
        pdf.cell(0, 5, f"Trust Score: {score}/100 ({level})", new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

        # Evidence
        evidence = ai_data.get("evidence", [])
        if evidence:
            pdf.set_font("Helvetica", "B", 9)
            pdf.cell(0, 5, "Evidence:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for ev in evidence[:6]:
                fn = ev.get("filename", "Unknown")
                pg = ev.get("page_number", "?")
                passage = ev.get("text", "") or ev.get("chunk_text", "")
                passage_trunc = passage[:120] + "…" if len(passage) > 120 else passage
                line = f"• {fn}, p.{pg}"
                if passage_trunc:
                    line += f': "{passage_trunc}"'
                pdf.set_text_color(60, 60, 60)
                pdf.multi_cell(0, 5, line)
                pdf.set_text_color(0, 0, 0)
            pdf.ln(1)

        # Warnings
        warnings = (ai_data.get("trust") or {}).get("warnings", [])
        if warnings:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(180, 83, 9)
            pdf.cell(0, 5, "Warnings:", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for w in warnings:
                pdf.multi_cell(0, 5, f"⚠ {w}")
            pdf.set_text_color(0, 0, 0)
            pdf.ln(1)

        # Contradictions
        if contradictions:
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(220, 38, 38)
            pdf.cell(0, 5, f"Contradictions detected ({len(contradictions)}):", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 9)
            for c in contradictions:
                da = c.get("doc_a", {})
                db = c.get("doc_b", {})
                pdf.multi_cell(
                    0, 5,
                    f"  {da.get('filename','?')} p.{da.get('page','?')}: \"{da.get('text','')}\" vs "
                    f"{db.get('filename','?')} p.{db.get('page','?')}: \"{db.get('text','')}\"",
                )
            pdf.set_text_color(0, 0, 0)

        # Separator
        pdf.ln(3)
        pdf.set_draw_color(200, 200, 200)
        pdf.cell(0, 0, "", border="T")

    # ── SUMMARY PAGE ─────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, "Summary Statistics", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    summary_rows = [
        ("Total queries", str(stats["total"])),
        ("High confidence answers", str(stats["high"])),
        ("Moderate confidence answers", str(stats["medium"])),
        ("Low confidence answers", str(stats["low"])),
        ("Contradictions detected", str(stats["contradictions"])),
        ("Documents analyzed", str(len(doc_filenames))),
    ]
    pdf.set_font("Helvetica", "", 10)
    for label, val in summary_rows:
        pdf.cell(100, 7, label, new_x="RIGHT", new_y="TOP")
        pdf.cell(0, 7, val, new_x="LMARGIN", new_y="NEXT")

    # Footer
    pdf.set_y(-15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, f"DocuMindAI Audit Report | {generated_at}", align="C")

    return io.BytesIO(pdf.output())


# ── DOCX ──────────────────────────────────────────────────────────────────────

def _build_docx(session, user: dict) -> io.BytesIO:
    from docx import Document as DocxDocument
    from docx.shared import Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH

    doc = DocxDocument()

    user_name = user.get("display_name") or user.get("name") or user.get("email", "Unknown")
    user_id_tail = str(user.get("id", ""))[-8:]
    generated_at = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    # Cover
    title = doc.add_heading("AI-Assisted Document Analysis Report", level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    doc.add_paragraph("Generated by DocuMindAI").alignment = WD_ALIGN_PARAGRAPH.CENTER  # type: ignore[attr-defined]

    doc_filenames: list[str] = []
    msg_pairs: list[tuple[str, str, dict]] = []
    messages = list(session.messages)
    i = 0
    while i < len(messages):
        msg = messages[i]
        if msg.role == "user":
            query_text = msg.content
            ts = msg.created_at.strftime("%Y-%m-%d %H:%M") if msg.created_at else "—"
            ai_data: dict = {}
            if i + 1 < len(messages) and messages[i + 1].role == "assistant":
                ai_data = _parse_message(messages[i + 1].content)
                for ev in ai_data.get("evidence", []):
                    fn = ev.get("filename", "")
                    if fn and fn not in doc_filenames:
                        doc_filenames.append(fn)
                i += 1
            msg_pairs.append((query_text, ts, ai_data))
        i += 1

    meta_items = [
        ("Session", session.title[:80]),
        ("Date", generated_at),
        ("Workspace", session.workspace_type.capitalize()),
        ("Documents analyzed", ", ".join(doc_filenames) or "—"),
        ("User", f"{user_name} (ID: ...{user_id_tail})"),
    ]
    for label, val in meta_items:
        p = doc.add_paragraph()
        r = p.add_run(f"{label}: ")
        r.bold = True
        p.add_run(val or "—")

    disc = doc.add_paragraph()
    dr = disc.add_run(f"DISCLAIMER: {_AUDIT_DISCLAIMER}")
    dr.italic = True
    dr.font.size = Pt(9)
    dr.font.color.rgb = RGBColor(120, 80, 0)

    doc.add_page_break()

    stats = {"total": 0, "high": 0, "medium": 0, "low": 0, "contradictions": 0}
    level_rgb = {"HIGH": RGBColor(22, 163, 74), "MEDIUM": RGBColor(180, 83, 9), "LOW": RGBColor(220, 38, 38)}

    for n, (query_text, ts, ai_data) in enumerate(msg_pairs, 1):
        stats["total"] += 1
        level = _trust_level(ai_data.get("trust"), ai_data.get("confidence_score", 0.0))
        score = _trust_score(ai_data.get("trust"), ai_data.get("confidence_score", 0.0))
        stats[level.lower()] = stats.get(level.lower(), 0) + 1
        contradictions = (ai_data.get("trust") or {}).get("contradictions", [])
        stats["contradictions"] += len(contradictions)

        h = doc.add_heading(f"Query #{n} — {ts}", level=2)

        p = doc.add_paragraph()
        p.add_run("Question: ").bold = True
        p.add_run(query_text)

        p = doc.add_paragraph()
        p.add_run("Answer: ").bold = True
        answer_text = (ai_data.get("answer") or "—").replace("**", "").replace("#", "")
        p.add_run(answer_text)

        p = doc.add_paragraph()
        ts_run = p.add_run(f"Trust Score: {score}/100 ({level})")
        ts_run.bold = True
        ts_run.font.color.rgb = level_rgb.get(level, RGBColor(80, 80, 80))

        for ev in (ai_data.get("evidence") or [])[:6]:
            fn = ev.get("filename", "Unknown")
            pg = ev.get("page_number", "?")
            passage = ev.get("text", "") or ev.get("chunk_text", "")
            passage_trunc = passage[:120] + "…" if len(passage) > 120 else passage
            ep = doc.add_paragraph(style="List Bullet")
            ep.add_run(f"{fn}, p.{pg}").bold = True
            if passage_trunc:
                ep.add_run(f': "{passage_trunc}"')

        for w in (ai_data.get("trust") or {}).get("warnings", []):
            wp = doc.add_paragraph()
            wr = wp.add_run(f"⚠ {w}")
            wr.font.color.rgb = RGBColor(180, 83, 9)
            wr.font.size = Pt(9)

        doc.add_paragraph("─" * 60)

    # Summary
    doc.add_page_break()
    doc.add_heading("Summary Statistics", level=1)
    tbl = doc.add_table(rows=1, cols=2)
    tbl.style = "Table Grid"
    hdr = tbl.rows[0].cells
    hdr[0].text = "Metric"
    hdr[1].text = "Value"
    rows_data = [
        ("Total queries", str(stats["total"])),
        ("High confidence", str(stats["high"])),
        ("Moderate confidence", str(stats["medium"])),
        ("Low confidence", str(stats["low"])),
        ("Contradictions detected", str(stats["contradictions"])),
        ("Documents analyzed", str(len(doc_filenames))),
    ]
    for label, val in rows_data:
        row = tbl.add_row().cells
        row[0].text = label
        row[1].text = val

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
