import os
import io
import logging
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

logger = logging.getLogger(__name__)

class ExportEngine:
    """
    PHASE 4: REAL EXPORT ENGINE
    Responsible for converting internal data structures into fully-formatted, downloadable files
    with strict layout, style, and citation preservation.
    """

    @staticmethod
    def generate_legal_redline_docx(contract_title: str, clauses: list) -> io.BytesIO:
        """
        Generates a DOCX file for a legal contract, applying 'Track Changes' style formatting 
        to AI redline suggestions.
        """
        document = Document()
        
        # Title
        title = document.add_heading(f"Contract Review: {contract_title}", level=0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        document.add_paragraph("Generated by DocuMindAI Legal Compliance Engine", style='Subtitle')
        
        document.add_page_break()

        for c in clauses:
            clause_data = c.get("clause", {})
            redlines = c.get("redlines", [])
            
            section_name = clause_data.get("section_name", "Unnamed Section")
            original_text = clause_data.get("original_text", "")
            risk = clause_data.get("risk_level", "UNKNOWN")
            
            # Clause Header
            h2 = document.add_heading(section_name, level=2)
            
            # Original Text
            p_orig = document.add_paragraph()
            p_orig.add_run("Original Text: ").bold = True
            p_orig.add_run(original_text)
            
            # Risk & Notes
            p_notes = document.add_paragraph()
            risk_run = p_notes.add_run(f"Risk Level: {risk}")
            if risk == "HIGH":
                risk_run.font.color.rgb = RGBColor(255, 0, 0)
            elif risk == "MEDIUM":
                risk_run.font.color.rgb = RGBColor(255, 165, 0)
            else:
                risk_run.font.color.rgb = RGBColor(0, 128, 0)
                
            if clause_data.get("compliance_notes"):
                document.add_paragraph(f"Audit Note: {clause_data.get('compliance_notes')}")
            
            # Redlines
            for r in redlines:
                p_red = document.add_paragraph()
                p_red.add_run("Suggested Redline: ").bold = True
                run_sugg = p_red.add_run(r.get("suggested_text", ""))
                run_sugg.font.color.rgb = RGBColor(0, 128, 0) # Green for additions/fixes
                
            document.add_paragraph("-" * 50)

        # Save to memory stream
        f = io.BytesIO()
        document.save(f)
        f.seek(0)
        return f

    @staticmethod
    def generate_research_synthesis_docx(project_title: str, synthesis_data: dict) -> io.BytesIO:
        """
        Generates a literature review DOCX from research synthesis data.
        """
        document = Document()
        
        document.add_heading(f"Literature Review: {project_title}", level=0)
        document.add_paragraph("Generated by DocuMindAI Research Copilot", style='Subtitle')
        
        document.add_heading("Executive Summary", level=1)
        document.add_paragraph("This document synthesizes findings across the uploaded literature, highlighting consensus topics and methodological contradictions.")
        
        # Contradictions
        if synthesis_data.get("contradictions"):
            document.add_heading("Detected Contradictions", level=2)
            for c in synthesis_data["contradictions"]:
                p = document.add_paragraph(style='List Bullet')
                p.add_run(f"[{c.get('severity', 'UNKNOWN')} RISK] ").bold = True
                p.add_run(c.get("description", ""))
                
        # Consensus
        if synthesis_data.get("clusters"):
            document.add_heading("Consensus Findings", level=2)
            for cluster in synthesis_data["clusters"]:
                document.add_heading(cluster.get("topic", "Topic"), level=3)
                p_score = document.add_paragraph()
                p_score.add_run(f"Confidence Score: {cluster.get('consensus_score', 0) * 100:.1f}%").italic = True
                
                for f in cluster.get("findings", []):
                    p = document.add_paragraph(f'"{f.get("statement", "")}"', style='Quote')
                    
        f = io.BytesIO()
        document.save(f)
        f.seek(0)
        return f

export_engine = ExportEngine()
