"""add_legal_models

Revision ID: 07c651c8dd4e
Revises: 8ec27d914474
Create Date: 2026-05-14 21:22:03.505561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '07c651c8dd4e'
down_revision: Union[str, None] = '8ec27d914474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_compliance_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('rule_description', sa.String(), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_compliance_rules_id'), 'legal_compliance_rules', ['id'], unique=False)
    op.create_index(op.f('ix_legal_compliance_rules_workspace_id'), 'legal_compliance_rules', ['workspace_id'], unique=False)
    op.create_table('legal_contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('party_name', sa.String(), nullable=True),
    sa.Column('contract_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_score', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_contracts_id'), 'legal_contracts', ['id'], unique=False)
    op.create_index(op.f('ix_legal_contracts_workspace_id'), 'legal_contracts', ['workspace_id'], unique=False)
    op.create_table('legal_approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['legal_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_approvals_id'), 'legal_approvals', ['id'], unique=False)
    op.create_index(op.f('ix_legal_approvals_workspace_id'), 'legal_approvals', ['workspace_id'], unique=False)
    op.create_table('legal_clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('clause_type', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('compliance_notes', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['legal_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_clauses_id'), 'legal_clauses', ['id'], unique=False)
    op.create_index(op.f('ix_legal_clauses_workspace_id'), 'legal_clauses', ['workspace_id'], unique=False)
    op.create_table('legal_redlines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('suggested_text', sa.String(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clause_id'], ['legal_clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['legal_compliance_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_redlines_id'), 'legal_redlines', ['id'], unique=False)
    op.create_index(op.f('ix_legal_redlines_workspace_id'), 'legal_redlines', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_legal_redlines_workspace_id'), table_name='legal_redlines')
    op.drop_index(op.f('ix_legal_redlines_id'), table_name='legal_redlines')
    op.drop_table('legal_redlines')
    op.drop_index(op.f('ix_legal_clauses_workspace_id'), table_name='legal_clauses')
    op.drop_index(op.f('ix_legal_clauses_id'), table_name='legal_clauses')
    op.drop_table('legal_clauses')
    op.drop_index(op.f('ix_legal_approvals_workspace_id'), table_name='legal_approvals')
    op.drop_index(op.f('ix_legal_approvals_id'), table_name='legal_approvals')
    op.drop_table('legal_approvals')
    op.drop_index(op.f('ix_legal_contracts_workspace_id'), table_name='legal_contracts')
    op.drop_index(op.f('ix_legal_contracts_id'), table_name='legal_contracts')
    op.drop_table('legal_contracts')
    op.drop_index(op.f('ix_legal_compliance_rules_workspace_id'), table_name='legal_compliance_rules')
    op.drop_index(op.f('ix_legal_compliance_rules_id'), table_name='legal_compliance_rules')
    op.drop_table('legal_compliance_rules')
    # ### end Alembic commands ###
