"""add_finance_vector

Revision ID: 0f6209734afa
Revises: 1234eb978f16
Create Date: 2026-05-14 21:33:05.920337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0f6209734afa'
down_revision: Union[str, None] = '1234eb978f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('finance_transactions', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('finance_transactions', 'embedding')
    # ### end Alembic commands ###
