"""add_finance_models

Revision ID: 1234eb978f16
Revises: 07c651c8dd4e
Create Date: 2026-05-14 21:30:08.758300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1234eb978f16'
down_revision: Union[str, None] = '07c651c8dd4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finance_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_documents_id'), 'finance_documents', ['id'], unique=False)
    op.create_index(op.f('ix_finance_documents_workspace_id'), 'finance_documents', ['workspace_id'], unique=False)
    op.create_table('finance_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_rules_id'), 'finance_rules', ['id'], unique=False)
    op.create_index(op.f('ix_finance_rules_workspace_id'), 'finance_rules', ['workspace_id'], unique=False)
    op.create_table('finance_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('financial_doc_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('anomaly_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_doc_id'], ['finance_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_transactions_id'), 'finance_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_finance_transactions_workspace_id'), 'finance_transactions', ['workspace_id'], unique=False)
    op.create_table('finance_audit_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('financial_doc_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('finding_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['financial_doc_id'], ['finance_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['finance_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finance_audit_findings_id'), 'finance_audit_findings', ['id'], unique=False)
    op.create_index(op.f('ix_finance_audit_findings_workspace_id'), 'finance_audit_findings', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finance_audit_findings_workspace_id'), table_name='finance_audit_findings')
    op.drop_index(op.f('ix_finance_audit_findings_id'), table_name='finance_audit_findings')
    op.drop_table('finance_audit_findings')
    op.drop_index(op.f('ix_finance_transactions_workspace_id'), table_name='finance_transactions')
    op.drop_index(op.f('ix_finance_transactions_id'), table_name='finance_transactions')
    op.drop_table('finance_transactions')
    op.drop_index(op.f('ix_finance_rules_workspace_id'), table_name='finance_rules')
    op.drop_index(op.f('ix_finance_rules_id'), table_name='finance_rules')
    op.drop_table('finance_rules')
    op.drop_index(op.f('ix_finance_documents_workspace_id'), table_name='finance_documents')
    op.drop_index(op.f('ix_finance_documents_id'), table_name='finance_documents')
    op.drop_table('finance_documents')
    # ### end Alembic commands ###
