"""add_hr_models

Revision ID: 2213cbb175d8
Revises: b636b7320f8f
Create Date: 2026-05-14 21:04:28.490128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2213cbb175d8'
down_revision: Union[str, None] = 'b636b7320f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_candidates_id'), 'hr_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_hr_candidates_workspace_id'), 'hr_candidates', ['workspace_id'], unique=False)
    op.create_table('hr_job_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_job_roles_id'), 'hr_job_roles', ['id'], unique=False)
    op.create_index(op.f('ix_hr_job_roles_workspace_id'), 'hr_job_roles', ['workspace_id'], unique=False)
    op.create_table('hr_job_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('fit_score', sa.Float(), nullable=True),
    sa.Column('match_analysis', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('recruiter_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['hr_candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['hr_job_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_job_matches_id'), 'hr_job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_hr_job_matches_workspace_id'), 'hr_job_matches', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_job_matches_workspace_id'), table_name='hr_job_matches')
    op.drop_index(op.f('ix_hr_job_matches_id'), table_name='hr_job_matches')
    op.drop_table('hr_job_matches')
    op.drop_index(op.f('ix_hr_job_roles_workspace_id'), table_name='hr_job_roles')
    op.drop_index(op.f('ix_hr_job_roles_id'), table_name='hr_job_roles')
    op.drop_table('hr_job_roles')
    op.drop_index(op.f('ix_hr_candidates_workspace_id'), table_name='hr_candidates')
    op.drop_index(op.f('ix_hr_candidates_id'), table_name='hr_candidates')
    op.drop_table('hr_candidates')
    # ### end Alembic commands ###
