"""add_research_models

Revision ID: 3cfcd82eefa5
Revises: 416d80423fd3
Create Date: 2026-05-14 21:45:14.527307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3cfcd82eefa5'
down_revision: Union[str, None] = '416d80423fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_id'), 'research_projects', ['id'], unique=False)
    op.create_index(op.f('ix_research_projects_workspace_id'), 'research_projects', ['workspace_id'], unique=False)
    op.create_table('research_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('abstract', sa.String(), nullable=True),
    sa.Column('published_year', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_papers_id'), 'research_papers', ['id'], unique=False)
    op.create_index(op.f('ix_research_papers_workspace_id'), 'research_papers', ['workspace_id'], unique=False)
    op.create_table('research_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('evidence_quote', sa.String(), nullable=True),
    sa.Column('methodology', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['research_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_findings_id'), 'research_findings', ['id'], unique=False)
    op.create_index(op.f('ix_research_findings_workspace_id'), 'research_findings', ['workspace_id'], unique=False)
    op.create_table('research_contradictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('finding_a_id', sa.UUID(), nullable=False),
    sa.Column('finding_b_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['finding_a_id'], ['research_findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_b_id'], ['research_findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_contradictions_id'), 'research_contradictions', ['id'], unique=False)
    op.create_index(op.f('ix_research_contradictions_workspace_id'), 'research_contradictions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_contradictions_workspace_id'), table_name='research_contradictions')
    op.drop_index(op.f('ix_research_contradictions_id'), table_name='research_contradictions')
    op.drop_table('research_contradictions')
    op.drop_index(op.f('ix_research_findings_workspace_id'), table_name='research_findings')
    op.drop_index(op.f('ix_research_findings_id'), table_name='research_findings')
    op.drop_table('research_findings')
    op.drop_index(op.f('ix_research_papers_workspace_id'), table_name='research_papers')
    op.drop_index(op.f('ix_research_papers_id'), table_name='research_papers')
    op.drop_table('research_papers')
    op.drop_index(op.f('ix_research_projects_workspace_id'), table_name='research_projects')
    op.drop_index(op.f('ix_research_projects_id'), table_name='research_projects')
    op.drop_table('research_projects')
    # ### end Alembic commands ###
