"""add_study_vectors

Revision ID: 416d80423fd3
Revises: 94fa93bb769d
Create Date: 2026-05-14 21:39:55.785972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '416d80423fd3'
down_revision: Union[str, None] = '94fa93bb769d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_flashcards', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('study_notes', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_notes', 'embedding')
    op.drop_column('study_flashcards', 'embedding')
    # ### end Alembic commands ###
