"""add_content_hash_and_source_to_documents

Revision ID: 87c96095e342
Revises: 2245e3e6d30c
Create Date: 2026-05-20 07:26:05.797476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87c96095e342'
down_revision: Union[str, None] = '2245e3e6d30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('line_item', sa.String(), nullable=False),
    sa.Column('extracted_value', sa.Float(), nullable=True),
    sa.Column('raw_text_span', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('table_row', sa.String(), nullable=True),
    sa.Column('table_column', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_audit_document_id'), 'extraction_audit', ['document_id'], unique=False)
    op.create_index(op.f('ix_extraction_audit_id'), 'extraction_audit', ['id'], unique=False)
    op.create_table('legal_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('overall_risk_score', sa.Integer(), nullable=True),
    sa.Column('overall_risk_level', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('clause_risks', sa.JSON(), nullable=True),
    sa.Column('missing_clauses', sa.JSON(), nullable=True),
    sa.Column('consistency_warnings', sa.JSON(), nullable=True),
    sa.Column('escalation_required', sa.Boolean(), nullable=True),
    sa.Column('escalation_reason', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('analysis_version', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('request_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_duration_ms', sa.Integer(), nullable=True),
    sa.Column('clause_count', sa.Integer(), nullable=True),
    sa.Column('missing_clause_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_analyses_contract_id'), 'legal_analyses', ['contract_id'], unique=False)
    op.create_index(op.f('ix_legal_analyses_document_id'), 'legal_analyses', ['document_id'], unique=False)
    op.create_index(op.f('ix_legal_analyses_id'), 'legal_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_legal_analyses_user_id'), 'legal_analyses', ['user_id'], unique=False)
    op.create_index(op.f('ix_legal_analyses_workspace_id'), 'legal_analyses', ['workspace_id'], unique=False)
    op.create_table('legal_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('event_detail', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_audit_log_id'), 'legal_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_legal_audit_log_timestamp'), 'legal_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_legal_audit_log_user_id'), 'legal_audit_log', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.create_index(op.f('ix_correction_notes_id'), 'correction_notes', ['id'], unique=False)
    op.create_index(op.f('ix_corrections_id'), 'corrections', ['id'], unique=False)
    op.add_column('documents', sa.Column('content_hash', sa.String(length=32), nullable=True))
    op.add_column('documents', sa.Column('source', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.drop_column('documents', 'display_name')
    op.drop_index(op.f('ix_eval_benchmark_is_active'), table_name='eval_benchmark_queries')
    op.drop_index(op.f('ix_eval_benchmark_workspace_id'), table_name='eval_benchmark_queries')
    op.create_index(op.f('ix_eval_benchmark_queries_id'), 'eval_benchmark_queries', ['id'], unique=False)
    op.create_index(op.f('ix_eval_benchmark_queries_workspace_id'), 'eval_benchmark_queries', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_eval_results_workspace_run_ts'), table_name='eval_results')
    op.create_index(op.f('ix_eval_results_id'), 'eval_results', ['id'], unique=False)
    op.create_index(op.f('ix_eval_results_run_timestamp'), 'eval_results', ['run_timestamp'], unique=False)
    op.create_index(op.f('ix_eval_results_workspace_id'), 'eval_results', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_message_notes_id'), 'message_notes', ['id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.drop_index(op.f('ix_report_shares_user_created'), table_name='report_shares')
    op.drop_constraint(op.f('report_shares_share_token_key'), 'report_shares', type_='unique')
    op.create_index(op.f('ix_report_shares_id'), 'report_shares', ['id'], unique=False)
    op.create_index(op.f('ix_report_shares_user_id'), 'report_shares', ['user_id'], unique=False)
    op.drop_index(op.f('ix_sqt_use_count'), table_name='saved_query_templates')
    op.drop_index(op.f('ix_sqt_user_id'), table_name='saved_query_templates')
    op.create_index(op.f('ix_saved_query_templates_id'), 'saved_query_templates', ['id'], unique=False)
    op.create_index(op.f('ix_saved_query_templates_user_id'), 'saved_query_templates', ['user_id'], unique=False)
    op.drop_index(op.f('ix_scheduled_reports_next_run'), table_name='scheduled_reports')
    op.create_index(op.f('ix_scheduled_reports_id'), 'scheduled_reports', ['id'], unique=False)
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('workspace_id', sa.String(length=50), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users', 'workspace_id')
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_scheduled_reports_id'), table_name='scheduled_reports')
    op.create_index(op.f('ix_scheduled_reports_next_run'), 'scheduled_reports', ['next_run_at', 'is_active'], unique=False)
    op.drop_index(op.f('ix_saved_query_templates_user_id'), table_name='saved_query_templates')
    op.drop_index(op.f('ix_saved_query_templates_id'), table_name='saved_query_templates')
    op.create_index(op.f('ix_sqt_user_id'), 'saved_query_templates', ['user_id'], unique=False)
    op.create_index(op.f('ix_sqt_use_count'), 'saved_query_templates', ['use_count'], unique=False)
    op.drop_index(op.f('ix_report_shares_user_id'), table_name='report_shares')
    op.drop_index(op.f('ix_report_shares_id'), table_name='report_shares')
    op.create_unique_constraint(op.f('report_shares_share_token_key'), 'report_shares', ['share_token'])
    op.create_index(op.f('ix_report_shares_user_created'), 'report_shares', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_message_notes_id'), table_name='message_notes')
    op.drop_index(op.f('ix_eval_results_workspace_id'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_run_timestamp'), table_name='eval_results')
    op.drop_index(op.f('ix_eval_results_id'), table_name='eval_results')
    op.create_index(op.f('ix_eval_results_workspace_run_ts'), 'eval_results', ['workspace_id', 'run_timestamp'], unique=False)
    op.drop_index(op.f('ix_eval_benchmark_queries_workspace_id'), table_name='eval_benchmark_queries')
    op.drop_index(op.f('ix_eval_benchmark_queries_id'), table_name='eval_benchmark_queries')
    op.create_index(op.f('ix_eval_benchmark_workspace_id'), 'eval_benchmark_queries', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_eval_benchmark_is_active'), 'eval_benchmark_queries', ['is_active'], unique=False)
    op.add_column('documents', sa.Column('display_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_column('documents', 'source')
    op.drop_column('documents', 'content_hash')
    op.drop_index(op.f('ix_corrections_id'), table_name='corrections')
    op.drop_index(op.f('ix_correction_notes_id'), table_name='correction_notes')
    op.create_table('bookmarks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('citations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False),
    sa.Column('workspace', sa.VARCHAR(), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('bookmarks_session_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookmarks_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('bookmarks_pkey'))
    )
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_legal_audit_log_user_id'), table_name='legal_audit_log')
    op.drop_index(op.f('ix_legal_audit_log_timestamp'), table_name='legal_audit_log')
    op.drop_index(op.f('ix_legal_audit_log_id'), table_name='legal_audit_log')
    op.drop_table('legal_audit_log')
    op.drop_index(op.f('ix_legal_analyses_workspace_id'), table_name='legal_analyses')
    op.drop_index(op.f('ix_legal_analyses_user_id'), table_name='legal_analyses')
    op.drop_index(op.f('ix_legal_analyses_id'), table_name='legal_analyses')
    op.drop_index(op.f('ix_legal_analyses_document_id'), table_name='legal_analyses')
    op.drop_index(op.f('ix_legal_analyses_contract_id'), table_name='legal_analyses')
    op.drop_table('legal_analyses')
    op.drop_index(op.f('ix_extraction_audit_id'), table_name='extraction_audit')
    op.drop_index(op.f('ix_extraction_audit_document_id'), table_name='extraction_audit')
    op.drop_table('extraction_audit')
    # ### end Alembic commands ###
