"""add_hr_collaboration_and_vector

Revision ID: 8ec27d914474
Revises: 2213cbb175d8
Create Date: 2026-05-14 21:17:08.893721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8ec27d914474'
down_revision: Union[str, None] = '2213cbb175d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_candidate_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['hr_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_candidate_notes_id'), 'hr_candidate_notes', ['id'], unique=False)
    op.create_index(op.f('ix_hr_candidate_notes_workspace_id'), 'hr_candidate_notes', ['workspace_id'], unique=False)
    op.create_table('hr_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('interviewer_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scorecard', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['hr_job_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_interviews_id'), 'hr_interviews', ['id'], unique=False)
    op.create_index(op.f('ix_hr_interviews_workspace_id'), 'hr_interviews', ['workspace_id'], unique=False)
    op.add_column('hr_candidates', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_candidates', 'embedding')
    op.drop_index(op.f('ix_hr_interviews_workspace_id'), table_name='hr_interviews')
    op.drop_index(op.f('ix_hr_interviews_id'), table_name='hr_interviews')
    op.drop_table('hr_interviews')
    op.drop_index(op.f('ix_hr_candidate_notes_workspace_id'), table_name='hr_candidate_notes')
    op.drop_index(op.f('ix_hr_candidate_notes_id'), table_name='hr_candidate_notes')
    op.drop_table('hr_candidate_notes')
    # ### end Alembic commands ###
