"""add_study_models

Revision ID: 94fa93bb769d
Revises: 0f6209734afa
Create Date: 2026-05-14 21:37:07.382250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fa93bb769d'
down_revision: Union[str, None] = '0f6209734afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_flashcard_decks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_flashcard_decks_id'), 'study_flashcard_decks', ['id'], unique=False)
    op.create_index(op.f('ix_study_flashcard_decks_workspace_id'), 'study_flashcard_decks', ['workspace_id'], unique=False)
    op.create_table('study_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_notes_id'), 'study_notes', ['id'], unique=False)
    op.create_index(op.f('ix_study_notes_workspace_id'), 'study_notes', ['workspace_id'], unique=False)
    op.create_table('study_quiz_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('responses', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_quiz_attempts_id'), 'study_quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_study_quiz_attempts_workspace_id'), 'study_quiz_attempts', ['workspace_id'], unique=False)
    op.create_table('study_flashcards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('front', sa.String(), nullable=False),
    sa.Column('back', sa.String(), nullable=False),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('repetition_count', sa.Integer(), nullable=True),
    sa.Column('easiness_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['study_flashcard_decks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_flashcards_id'), 'study_flashcards', ['id'], unique=False)
    op.create_index(op.f('ix_study_flashcards_workspace_id'), 'study_flashcards', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_flashcards_workspace_id'), table_name='study_flashcards')
    op.drop_index(op.f('ix_study_flashcards_id'), table_name='study_flashcards')
    op.drop_table('study_flashcards')
    op.drop_index(op.f('ix_study_quiz_attempts_workspace_id'), table_name='study_quiz_attempts')
    op.drop_index(op.f('ix_study_quiz_attempts_id'), table_name='study_quiz_attempts')
    op.drop_table('study_quiz_attempts')
    op.drop_index(op.f('ix_study_notes_workspace_id'), table_name='study_notes')
    op.drop_index(op.f('ix_study_notes_id'), table_name='study_notes')
    op.drop_table('study_notes')
    op.drop_index(op.f('ix_study_flashcard_decks_workspace_id'), table_name='study_flashcard_decks')
    op.drop_index(op.f('ix_study_flashcard_decks_id'), table_name='study_flashcard_decks')
    op.drop_table('study_flashcard_decks')
    # ### end Alembic commands ###
