"""add_exam_models

Revision ID: b636b7320f8f
Revises: 928b99e2fba8
Create Date: 2026-05-14 20:13:39.219560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b636b7320f8f'
down_revision: Union[str, None] = '928b99e2fba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('share_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_id'), 'exam_papers', ['id'], unique=False)
    op.create_index(op.f('ix_exam_papers_share_token'), 'exam_papers', ['share_token'], unique=True)
    op.create_index(op.f('ix_exam_papers_workspace_id'), 'exam_papers', ['workspace_id'], unique=False)
    op.create_table('exam_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_versions_id'), 'exam_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_versions_id'), table_name='exam_versions')
    op.drop_table('exam_versions')
    op.drop_index(op.f('ix_exam_papers_workspace_id'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_share_token'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_id'), table_name='exam_papers')
    op.drop_table('exam_papers')
    # ### end Alembic commands ###
